# Generated by Django 2.2.5 on 2020-06-28 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, default='', max_length=20)),
                ('html', models.TextField(blank=True)),
                ('change', models.BooleanField(default=False)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
