# Generated by Django 2.2.5 on 2020-07-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_auto_20200628_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='html',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='domain',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
