# Generated by Django 2.2.5 on 2020-07-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20200719_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='html',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='domain',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
